import AppKit
import Foundation

/// Puts dictated text on a pasteboard for one paste, then puts back what was there before.
///
/// The text is marked concealed (and transient when it will be restored), the nspasteboard.org
/// conventions clipboard managers honour, so dictations stay out of clipboard history. The
/// previous contents come back after `restoreDelay` only if the pasteboard still holds Deck's
/// text: anything copied in between wins. A burst of dictations keeps the clipboard from before
/// the first one, never Deck's own earlier text. Main thread only.
public final class ClipboardSession {
    public static let shared = ClipboardSession(pasteboard: .general)

    static let marker = NSPasteboard.PasteboardType("com.yahya.deck.dictation")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private let pb: NSPasteboard
    private var saved: [[NSPasteboard.PasteboardType: Data]]?
    private var ownChangeCount: Int?
    private var restoreWork: DispatchWorkItem?

    /// Long enough for slow targets (Electron apps) to read the paste before the old contents return.
    public var restoreDelay: TimeInterval = 0.8

    public init(pasteboard: NSPasteboard) { pb = pasteboard }

    /// True while the pasteboard still holds the last text this session wrote.
    public var holdsOwnText: Bool { ownChangeCount != nil && pb.changeCount == ownChangeCount }

    /// Writes `text`. With `restore`, the previous contents come back after `restoreDelay`;
    /// without it, the text stays on the clipboard for the user to paste by hand.
    public func put(_ text: String, restore: Bool) {
        restoreWork?.cancel(); restoreWork = nil
        if !holdsOwnText || saved == nil { saved = snapshot() }
        pb.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: Self.concealed)
        item.setData(Data(), forType: Self.marker)
        if restore {
            item.setData(Data(), forType: Self.transient)
            item.setData(Data(), forType: Self.autoGenerated)
        }
        pb.writeObjects([item])
        ownChangeCount = pb.changeCount
        if restore { scheduleRestore() } else { saved = nil }
    }

    private func scheduleRestore() {
        let expected = ownChangeCount
        let work = DispatchWorkItem { [weak self] in
            guard let self else { return }
            let items = self.saved
            self.saved = nil; self.ownChangeCount = nil; self.restoreWork = nil
            guard self.pb.changeCount == expected, let items else { return }
            self.write(items)
        }
        restoreWork = work
        DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay, execute: work)
    }

    private func snapshot() -> [[NSPasteboard.PasteboardType: Data]] {
        (pb.pasteboardItems ?? []).map { item in
            var types: [NSPasteboard.PasteboardType: Data] = [:]
            for t in item.types { if let data = item.data(forType: t) { types[t] = data } }
            return types
        }
    }

    /// Restored contents are marked transient so clipboard managers don't log them a second time.
    private func write(_ items: [[NSPasteboard.PasteboardType: Data]]) {
        pb.clearContents()
        guard !items.isEmpty else { return }
        pb.writeObjects(items.map { types in
            let item = NSPasteboardItem()
            for (t, data) in types { item.setData(data, forType: t) }
            if types[Self.transient] == nil { item.setData(Data(), forType: Self.transient) }
            return item
        })
    }
}
